image: gcc

stages:
  - test

autotest:
  stage: test
  script:
    - ./bootstrap.sh
    - ./configure
    - make -j4 check
  artifacts:
    paths:
      - autotest.json
    expire_in: 1 month

benchmark:
  stage: test
  script:
    - ./bootstrap.sh
    - ./configure
    - make -j4 bench
  artifacts:
    paths:
      - benchmark.json
    expire_in: 1 month

