image: gcc

stages:
  - build
  - test

compile:
  stage: build
  script:
    - ./bootstrap.sh
    - ./configure
    - make -j4
  artifacts:
    paths:
      - makefile
      - configure
      - config.h
      - libliquid*
      - src/*/src/*.o

check:
  stage: test
  script:
    - make -j4 check
  artifacts:
    paths:
      - autotest.json
    expire_in: 1 month

bench:
  stage: test
  script:
    - make -j4 bench
  artifacts:
    paths:
      - benchmark.json
    expire_in: 1 month

